/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTerraFarmingRouteImport } from './routes/projects.terra-farming'
import { Route as ProjectsBigLeagueSwingsRouteImport } from './routes/projects.big-league-swings'
import { Route as BlogHowToBuildCustomAiAgentsRouteImport } from './routes/blog.how-to-build-custom-ai-agents'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTerraFarmingRoute = ProjectsTerraFarmingRouteImport.update({
  id: '/projects/terra-farming',
  path: '/projects/terra-farming',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBigLeagueSwingsRoute = ProjectsBigLeagueSwingsRouteImport.update({
  id: '/projects/big-league-swings',
  path: '/projects/big-league-swings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToBuildCustomAiAgentsRoute =
  BlogHowToBuildCustomAiAgentsRouteImport.update({
    id: '/blog/how-to-build-custom-ai-agents',
    path: '/blog/how-to-build-custom-ai-agents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-build-custom-ai-agents': typeof BlogHowToBuildCustomAiAgentsRoute
  '/projects/big-league-swings': typeof ProjectsBigLeagueSwingsRoute
  '/projects/terra-farming': typeof ProjectsTerraFarmingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-build-custom-ai-agents': typeof BlogHowToBuildCustomAiAgentsRoute
  '/projects/big-league-swings': typeof ProjectsBigLeagueSwingsRoute
  '/projects/terra-farming': typeof ProjectsTerraFarmingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-build-custom-ai-agents': typeof BlogHowToBuildCustomAiAgentsRoute
  '/projects/big-league-swings': typeof ProjectsBigLeagueSwingsRoute
  '/projects/terra-farming': typeof ProjectsTerraFarmingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/how-to-build-custom-ai-agents'
    | '/projects/big-league-swings'
    | '/projects/terra-farming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/how-to-build-custom-ai-agents'
    | '/projects/big-league-swings'
    | '/projects/terra-farming'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/how-to-build-custom-ai-agents'
    | '/projects/big-league-swings'
    | '/projects/terra-farming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogHowToBuildCustomAiAgentsRoute: typeof BlogHowToBuildCustomAiAgentsRoute
  ProjectsBigLeagueSwingsRoute: typeof ProjectsBigLeagueSwingsRoute
  ProjectsTerraFarmingRoute: typeof ProjectsTerraFarmingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/terra-farming': {
      id: '/projects/terra-farming'
      path: '/projects/terra-farming'
      fullPath: '/projects/terra-farming'
      preLoaderRoute: typeof ProjectsTerraFarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/big-league-swings': {
      id: '/projects/big-league-swings'
      path: '/projects/big-league-swings'
      fullPath: '/projects/big-league-swings'
      preLoaderRoute: typeof ProjectsBigLeagueSwingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-build-custom-ai-agents': {
      id: '/blog/how-to-build-custom-ai-agents'
      path: '/blog/how-to-build-custom-ai-agents'
      fullPath: '/blog/how-to-build-custom-ai-agents'
      preLoaderRoute: typeof BlogHowToBuildCustomAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogHowToBuildCustomAiAgentsRoute: BlogHowToBuildCustomAiAgentsRoute,
  ProjectsBigLeagueSwingsRoute: ProjectsBigLeagueSwingsRoute,
  ProjectsTerraFarmingRoute: ProjectsTerraFarmingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
